name: temp-env-cleanup

concurrency:
    group: temp-env-cleanup-${{ github.ref }}
    cancel-in-progress: true

on:
    workflow_dispatch:
    delete:
        # unfortunately, branch filters are not working for delete events, they are here for documentation purposes to identify the branches that should trigger this workflow
        branches:
            - 'major/*'
            - 'hotfix/*'

jobs:
    cleanup:
        # additional checks as the branch filters are not working for delete events
        if: ${{ contains(github.event.ref, 'major/') || contains(github.event.ref, 'hotfix/') }}
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Cleanup
              uses: Panenco/git-flow/cleanup@master
              with:
                  workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.SERVICE_ACCOUNT }}
                  delimiter: '-'
