name: test workflow

on:
    workflow_dispatch:
    delete:


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   name: Get feature name
                id: feature
                uses: Panenco/git-flow/feature@master
                with:
                    delimiter: '/'

            -   name: Set feature name
                run: |
                    echo '
                    ## Feature name
                    ${{ steps.feature.outputs.feature_name }}
                    ' >> $GITHUB_STEP_SUMMARY
